<?php

use Fisharebest\Webtrees\Fact;

/**
 * @var Fact $fact
 */

?>


<?php if (preg_match_all('/\n(2 SOUR\b.*(?:\n[^2].*)*)/', $fact->gedcom(), $matches, PREG_SET_ORDER) > 0) : ?>
    <?php $records = "" ?>
    <?php foreach ($matches as $match) : ?>
        <?php $records .= trim(view('fact-gedcom-fields', ['gedcom' => $match[1], 'parent' => $fact->tag(), 'tree' => $fact->record()->tree()])) ?>
    <?php endforeach ?>
    <?php $record_count = (substr_count($records, 'data-bs-toggle') > 0) ? substr_count($records, 'data-bs-toggle') : 0; ?>
    <?php $record_count = ($record_count > 0) ? $record_count : 1; ?>
    
    <?php if ($record_count > 1) : ?>        
        <a href="#sources-<?= e($fact->id()) ?>" role="button" data-bs-toggle="collapse" aria-controls="<?= e($fact->id()) ?>" aria-expanded="false">
            <?= view('icons/expand') ?>
            <?= view('icons/collapse') ?>
        </a>
        <span class="label">Sources (<?= $record_count ?>)</span>
        <div id="sources-<?= e($fact->id()) ?>" class="ps-4 collapse">  
            <div class="wt-fact-sources mt-2">
                <?= $records ?>
            </div>
        </div>
    <?php elseif ($record_count == 1) : ?>        
        <?= $records ?>
    <?php endif ?>

<?php endif ?>
