<?php
$view = view('::individual-page', get_defined_vars());

// Extract the title
$pattern = '/<h2 class="wt-page-title.*?<\/h2>/s';
preg_match($pattern, $view, $matches);
$pageTitleDiv = $matches[0] ?? '';

// remove comma, move dates/age to next line
$modifiedPageTitleDiv = str_replace(',', '<br>', $pageTitleDiv);

// update view
$view = str_replace($pageTitleDiv, $modifiedPageTitleDiv, $view);

// Display the modified view
echo $view;
?> 