<?php

use Fisharebest\Webtrees\Auth;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\Module\ModuleSidebarInterface;
use Fisharebest\Webtrees\Module\ModuleTabInterface;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\Http\RequestHandlers\UserListPage;
use Fisharebest\Webtrees\User;
use Illuminate\Support\Collection;

/**
 * @var string                                 $age
 * @var bool                                   $can_upload_media
 * @var Collection<int,Fact>                   $clipboard_facts
 * @var Collection<int,Media>                  $individual_media
 * @var Individual                             $record
 * @var Collection<int,string>                 $shares
 * @var Collection<int,ModuleSidebarInterface> $sidebars
 * @var Collection<int,ModuleTabInterface>     $tabs
 * @var Tree                                   $tree
 * @var Collection<int,User>                   $users
 */
?>

<?= view('individual-page-pending', ['record' => $record]) ?>
<div>
    <div class="individual-header individual-header-start" style="display: table">
        <table id=individual-header-table>
            <tr>
                <td rowspan=2 width=90px>
                    <?= view('individual-page-images', ['can_upload_media' => $can_upload_media, 'individual_media' => $individual_media, 'record' => $record, 'tree' => $tree]) ?>
                </td>
                <td rowspan=2 width=5px></td>
                <td colspan=2 valign=middle>
                    <h2 class="wt-page-title mx-auto my-0">
                        <?php if ($record->getBirthDate()->isOK() || $record->getDeathDate()->isOK()) : ?>
                            <?= $record->fullName() ?><br>
                            <?php if ($record->sex() === 'F') : ?>
                            <span class="wt-icon-sex wt-icon-sex-f"><i class="fas fa-venus fa-fw" aria-hidden="true"></i></span>
                            <?php elseif ($record->sex() === 'M') : ?>
                            <span class="wt-icon-sex wt-icon-sex-m"><i class="fas fa-mars fa-fw" aria-hidden="true"></i></span>
                            <?php elseif ($record->sex() === 'X') : ?>
                            <span class="wt-icon-sex wt-icon-sex-x"><i class="fas fa-transgender fa-fw" aria-hidden="true"></i></span>
                            <?php elseif ($record->sex() === 'U') : ?>
                            <span class="wt-icon-sex wt-icon-sex-u"><i class="fas fa-genderless fa-fw" aria-hidden="true"></i></span>
                            <?php endif ?>                         
                            <?= $record->lifespan() ?>
                        <?php else: ?>
                            <?= $record->fullName() ?>
                        <?php endif ?></?>
                        <?= $age ?>
                        </h2>   
                </td>
            </tr>        
            <tr>
                <td>
                    <ul id="tree-link" class="horizontal-list">                                                       
                        <li class="nav-item dropdown menu-chart" style="padding:0">
                            <a id=tree-link href="../../hourglass-3-1/<?= $record->xref() ?>" class="nav-link" role="button">&nbsp;View Tree</a>                              
                        </li>
                    </ul>                    
                </td>
                <td align=right valign=middle style="padding-right:10px">
                <div>
    <?php if ($record->canEdit()) : ?>
                            <?php $edit_button = view('individual-page-menu', ['can_upload_media' => $can_upload_media, 'clipboard_facts' => $clipboard_facts, 'record' => $record, 'shares' => $shares]) ?>
                            <?= preg_replace('/aria-expanded="false"[\s\S]+?<\/button>/', 'aria-expanded="false"><i class="fa fa-pencil" aria-hidden="true"></i></button>', $edit_button) ?>
                        <?php endif ?>    
</div>
    </td>
                </tr>

        </table>
    </div>

    <div class="row">
        <div class="col-sm-8">
            <?= view('individual-page-tabs', ['record' => $record, 'tabs' => $tabs]) ?>
        </div>

        <div class="col-sm-4">
            <?= view('individual-page-sidebars', ['record' => $record, 'sidebars' => $sidebars]) ?>
        </div>
    </div>


<?= view('modals/ajax') ?>
<?= view('modals/shares', ['shares' => $shares, 'title' => I18N::translate('Share') . ' — ' . $record->fullName()]) ?>

