<?php
use Fisharebest\Webtrees\Auth;

function getPalette(): string
{
    $palette = Auth::user()->getPreference("modern-palette", "");

    if ($palette === "") {
        $palette = "modern-default";
    }

    return $palette;
}

function getColors(): array
{
    $palette = getPalette();
    $background_color = "#FFFFFF";
    $theme_color = "#2694e8";
    switch ($palette) {
        case "modern-default":
            $background_color = "#F4F7FC";
            $theme_color = "#3644D9";
            break;
        case "modern-plain":
            $background_color = "#FFFFFF";
            $theme_color = "#FFFFFF";
            break;
        case "modern-ancestry":
            $background_color = "#F6F3F0";
            $theme_color = "#000000";
            break;
        case "bootswatch-cerulean":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-cosmo":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-cyborg":
            $background_color = "#f9f9f9";
            $theme_color = "#000000";
            break;
        case "bootswatch-darkly":
            $background_color = "#222222";
            $theme_color = "#222222";
            break;
        case "bootswatch-flatly":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-journal":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-litera":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-lumen":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-lux":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-materia":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-minty":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-morph":
            $background_color = "#D9E3F1";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-pulse":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-quartz":
            $background_color = "#686DC3";
            $theme_color = "#686DC3";
            break;
        case "bootswatch-sandstone":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-simplex":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-sketchy":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-spacelab":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-superhero":
            $background_color = "#0F2537";
            $theme_color = "#0F2537";
            break;
        case "bootswatch-united":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-vapor":
            $background_color = "#1A0933";
            $theme_color = "#1A0933";
            break;
        case "bootswatch-yeti":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
        case "bootswatch-zephyr":
            $background_color = "#f9f9f9";
            $theme_color = "#FFFFFF";
            break;
    }
    return [$background_color, $theme_color];
}

[$background_color, $theme_color] = getColors();
?>

<?= json_encode(
    (object) [
        "name" => "webtrees",
        "short_name" => "webtrees",
        "description" => "webtrees online genealogy",
        "scope" => "/",
        "start_url" => "/",
        "background_color" => $background_color,
        "theme_color" => $theme_color,
        "display" => "standalone",
        "icons" => [
            (object) [
                "src" => asset("favicon-192.png"),
                "sizes" => "192x192",
                "type" => "image/png",
            ],
        ],
    ],
    JSON_THROW_ON_ERROR
) ?>
