<?php

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Media;
use Fisharebest\Webtrees\MediaFile;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

/**
 * @var int                    $block_id
 * @var int                    $delay
 * @var Collection<Family>     $linked_families
 * @var Collection<Individual> $linked_individuals
 * @var Collection<Source>     $linked_sources
 * @var Media                  $media
 * @var MediaFile              $media_file
 * @var bool                   $show_controls
 * @var bool                   $start_automatically
 * @var Tree                   $tree
 */

?>

<?php
$code = $media_file->displayImage(200, 200, "cover", ["class" => "slide-show-image img-fluid"]);

// Extract the src attribute value
preg_match('/src="([^"]+)"/', $code, $matches);
$src = $matches[1];
?>

<style>
div.wt-slide-show-container {
  position: relative;
  z-index: 1;
}

div.wt-slide-show-container:before {
  position: absolute;
  border-radius: 20px;
  top: 0;
  right: 0;
  left: 0;
  height: 100%;
  width: 100%;
  background: url("<?= htmlspecialchars_decode($src) ?>") no-repeat center center /cover;
  content: '';
  -webkit-filter: blur(5px);
  filter: blur(5px), alpha(opacity=10);
  z-index: -1;
  opacity: 0.15;
  box-shadow: 0 0 8px 8px white inset;   
}

</style>  

<div class="wt-slide-show-container">
<div id=slide-show-content>
    <?php if ($show_controls) : ?>
        <div class="wt-slide-show-controls text-center">
            <a href="#" title="<?= I18N::translate('Play') ?>" <?= $start_automatically ? 'hidden' : '' ?>>
                <?= view('icons/media-play') ?>
                <span class="visually-hidden"><?= I18N::translate('Play') ?></span>
            </a>
            <a href="#" title="<?= I18N::translate('Stop') ?>" <?= $start_automatically ? '' : 'hidden' ?>>
                <?= view('icons/media-stop') ?>
                <span class="visually-hidden"><?= I18N::translate('Stop') ?></span>
            </a>
            <a href="#" title="<?= I18N::translate('Next image') ?>">
                <?= view('icons/media-next') ?>
                <span class="visually-hidden"><?= I18N::translate('Next image') ?></span>
            </a>
        </div>
    <?php endif ?>

    <figure class="wt-slide-show-figure text-center">
        <?= $media_file->displayImage(200, 200, 'contain', ['class' => 'slide-show-image img-fluid']) ?>
        <figcaption class="wt-slide-show-figcaption">
            <a href="<?= e($media->url()) ?>">
                <b><?= $media->fullName() ?></b>
            </a>
        </figcaption>
    </figure>

    <p class="wt-slide-show-notes text-center">
        <?php foreach ($media->facts(['NOTE']) as $fact) : ?>
            <?= view('fact-gedcom-fields', ['gedcom' => $fact->gedcom(), 'parent' => $media->tag(), 'tree' => $tree]) ?>
        <?php endforeach ?>
    </p>
    
    <div id=slide-show-links-container>
    <ul class="fa-ul wt-slide-show-links">
        <?php foreach ($linked_individuals as $individual) : ?>
            <li>               
                <a href="<?= e($individual->url()) ?>" class="wt-slide-show-link">
                    <?php if ($individual->tree()->getPreference('SHOW_HIGHLIGHT_IMAGES')) : ?>
                        <div class="fa-li">
                            <?= preg_replace('#<a.*?>(.*?)</a>#i', '\1', $individual->displayImage(40, 50, 'crop', ['class' => 'wt-chart-box-thumbnail'])) ?>
                    </div>
                    <?php else : ?> 
                        <span class="fa-li" title="<?= I18N::translate('Individual') ?>"><?= view('icons/individual') ?></span>
                    <?php endif ?>                  
                    <?= $individual->fullName() ?>
                </a>
            </li>
        <?php endforeach ?>

        <?php foreach ($linked_families as $family) : ?>
            <li>
                <span class="fa-li" title="<?= I18N::translate('Family') ?>"><?= view('icons/family') ?></span>
                <a href="<?= e($family->url()) ?>" class="wt-slide-show-link">
                    <?= $family->fullName() ?>
                </a>
            </li>
        <?php endforeach ?>

        <?php foreach ($linked_sources as $source) : ?>
            <li>
                <span class="fa-li" title="<?= I18N::translate('Source') ?>"><?= view('icons/source') ?></span>
                <a href="<?= e($source->url()) ?>" class="wt-slide-show-link">
                    <?= $source->fullName() ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
        </div>

        </div>
</div>

<script>
    var play = <?= json_encode($start_automatically, JSON_THROW_ON_ERROR) ?>;

    if (play) {
        var timeout = setTimeout(slideShowReload, <?= json_encode($delay * 1000, JSON_THROW_ON_ERROR) ?>);
    }

    function slideShowReload() {
        var block = $("#block-<?= $block_id ?>").parent();
        clearTimeout(timeout);
        block.load(block.data("wtAjaxUrl") + "&start=" + (play ? "1" : "0"));

        return false;
    }

    $(".wt-icon-media-play").on("click", function () {
        $(".wt-icon-media-play").parent().attr("hidden", true);
        $(".wt-icon-media-stop").parent().attr("hidden", false);
        play = true;
        return slideShowReload();
    });

    $(".wt-icon-media-stop").on("click", function () {
        $(".wt-icon-media-stop").parent().attr("hidden", true);
        $(".wt-icon-media-play").parent().attr("hidden", false);
        play = false;
        clearTimeout(timeout);
        return false;
    });

    $(".wt-icon-media-next").on("click", function () {
        return slideShowReload();
    });
</script>
