<?php
use Fisharebest\Webtrees\I18N;

use Fisharebest\Webtrees\Module\ModuleThemeInterface;


// Used for getting tree URL
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\Http\RequestHandlers\TreePage;

/**
 * @var Tree                   $tree
 */

$tree_url = e(route(TreePage::class, ['tree' => $tree->name()]));

$view = view('::layouts/default', get_defined_vars());

// Extract site title
preg_match('/<h1 class="col wt-site-title">(.*?)<\/h1>/s', $view, $siteTitle);
$siteTitle = '<div class="col wt-site-logo"></div>' . $siteTitle[1] ?? '';

// Extract search box
preg_match('/<form[^>]+class="[^"]*wt-header-search-form[^"]*"[^>]*>(.*?)<\/form>/s', $view, $searchBox);
$searchBox = $searchBox[0] ?? '';

// Extract primary navigation menu
preg_match('/<nav class="col wt-primary-navigation">.*?<ul class="nav wt-genealogy-menu">(.*?)<\/ul>/s', $view, $primaryNavigation);
$primaryNavigation = $primaryNavigation[1] ?? '';

// Extract secondary navigation menu
preg_match('/<div class="col wt-secondary-navigation">\s*<ul class="nav wt-user-menu">(.*?)<\/ul>\s*<\/div>/s', $view, $secondaryNavigation);
$secondaryNavigation = $secondaryNavigation[1] ?? '';

?>

<?= $view ?>

<nav class="navbar fixed-top ps-2 py-1" id=navbarMobile>
  <a class="navbar" href="<?= e($tree_url) ?>" id=navbarMobileTitle>
    <?= $siteTitle ?>
  </a>

  <!-- <div style="margin-left: auto; display: flex; align-items: center; justify-content: flex-end;">
  <div class="nav-item menu-list" style="font-size: 24px !important; padding-right: 10px">
    <a class="nav-link" href="<?= e($tree_url) . '/individual-list?show_all=yes' ?>"></a>
  </div>

  <div class="nav-item menu-search" style="font-size: 24px !important">
    <a class="nav-link" href="<?= e($tree_url) . '/search-general' ?>"></a>
  </div> -->
</div>


  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarContent">
    <form class="form-inline my-2 my-lg-0">
      <?= $searchBox ?>
    </form>    
    <span style="font-weight: 700; font-size: 16px; padding-top: 10px"><?= I18N::translate('MAIN MENU') ?></span>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <?= $primaryNavigation ?>
    </ul>
    <hr>
    <span style="font-weight: 700; font-size: 16px"><?= I18N::translate('SETTINGS') ?></span>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">      
      <?= $secondaryNavigation ?>
    </ul>
  </div>
</nav>

<!-- required for nav toggler/menu -->
<script src="<?= e(app(ModuleThemeInterface::class)->assetUrl('js/bootstrap.min.js')) ?>"></script>